name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  pytest:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f ci/requirements.txt ]; then pip install -r ci/requirements.txt; fi

    - name: Generate Report
      run: |
        coverage run -m pytest
        pwd
        coverage xml -i -o test-results-${{ matrix.python-version }}.xml

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: test-results-${{ matrix.python-version }}.xml