name: Build distribution

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

jobs:
  publish:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install build dependencies
        run: python -m pip install build wheel

      - name: Build distributions
        shell: bash -l {0}
        run: python setup.py sdist bdist_wheel

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Publish package to PyPI
        if: ${{ (github.repository == 'GMoncrieff/saeonobspy') && (github.event_name == 'push') && (startsWith(github.event.ref, 'refs/tags')) }}
        uses: pypa/gh-action-pypi-publish@v1.8.3
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}